### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by bunyaminn** [bounswe/bounswe2015group3#228]
please review my commit in here 

https://github.com/bounswe/bounswe2015group3/commit/c9adcc6aba0bb7608d71e22bb418ee27ecd25ef7

**Comment by danishjo** [comment]
The purpose of this code was to create a search bar for searching people, events, groups and all (people or event or group). Therefore, it would be better to have a select option next to a search text input. This code does what was expected in the project. It uses Bootstrap UI framework which is the most popular responsive user interface framework used by developers. In the code, grid method is used because it is one of the main rules regarding human-computer interaction. The first two grids are selected for the logo section, six grids are used for the search method and the final four grids are chosen for the navigation menu such as groups, events and sign-out.
Inline form class is used for placing the form in one row. Beside form-group class is used in order to bring the inputs together.
Search bar includes a text input. Beside there is select option which enables user to select one of the four options: all, event, group and people. Next to the select option we have a submit button which has a beautiful search icon (this feature comes from the font-awesome pakage)[ http://fontawesome.io/icons/].
Code is pretty clear.
