### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by cankurtan** [bounswe/bounswe2015group3#230]
Please review my commit https://github.com/bounswe/bounswe2015group3/commit/67685ba0ee30dfa0ef1807a83cfc739472cc60ed

**Comment by umutafacan** [comment]
At the first look code organisation looks very well. Certainly i can say that easy to understand the how it work and modify it. By the way it looks has no mistake or undone part. The naming of variables are suitable with project's other part and general java coding styles. Also deleting unused frameworks from head of class is good to performance and readability. One question for the naming of endpoints, maybe the naming can be like that "groups/post/update" instead of "group/update/post". However it does not cause any problem or confusion. When it comes to jsp classes, they are very well coded by perspective and features as i mentioned above.  Personally, i appreciate to your work.
