### ISSUE TITLE
CodeReview: #209 - 8360bbb

### ISSUE THREAD

**Issue by umutafacan** [bounswe/bounswe2015group3#232]
Event function code review is needed.

**Comment by cankurtan** [comment]
(You can see the same review under commit. It will be easier to follow review under commit)

Seeing lots of work in one commit is a good thing. Your code is well structed. Design of your functions is very well. Giving data to sql query as a parameter is good for safety. If you build a string with that parameters it may cause to a leak in the system. You did very well by giving them as parameter. There is a problem with writing Long instead of long. Long is general class, long is a primitive type. Also same for int, bool etc. You can find further information here:
http://illegalargumentexception.blogspot.com.tr/2008/08/java-int-versus-integer.html

You need javadoc type comment before your functions to give information about what that function does. One more addition: if workspace.xml is something special to your system, put it into gitignore file.

In general, it is a pretty good job!
