### ISSUE TITLE
Code review for group page user interface

### ISSUE THREAD

**Issue by danishjo** [bounswe/bounswe2015group3#237]
Can you please review my code? The code is about creating a page for frontend user interface of the group which has the following specifications.
- A banner image which describes the group
- Group Name and below that you can finde number of members and posts.
- Right sidebar includes button for joining or leaving the group and name of the group members
- In the body part,  A text are for writing a post and list of posts that are belong the group is also included.
- Finally, a footer is included which has a link to the wiki page of our project.

Here is the code ==> f06cc7202a8fb680cdc544a73850cceb5eab5f68

**Comment by bunyaminn** [comment]
The code is pretty clear and straight to the point. All structures used in constructs are well defined. No fancy, long and hard to understand variable names are used. Indentation pretty nicely done.  Also, I didn't find any bug in this codeHowever there are little comments in the code.
It uses Bootstrap UI framework which is the most popular responsive user interface framework used by developers. In the code, grid method is used because it is one of the main rules regarding human-computer interaction.
Overall the code is clear and readable. I can easily understand and make modifications on the given commit.

Regards.

**Comment by danishjo** [comment]
Thank you very much :+1:

**Comment by bunyaminn** [comment]
I think Nakip reopen this issue wrongly. It has been already completed.
