### ISSUE TITLE
Review code

### ISSUE THREAD

**Issue by tuba-topaloglu** [bounswe/bounswe2015group3#238]
my commit: c6657107c761926939973e0781a42d12813ad685

Could you please review the commit I mentioned? 
In this commit, I added API methods related to event posts and comments to our Android application.

**Comment by BurakYilmaz92** [comment]
In terms of readability, your code is great. Meaningful variable names and indentation really help me understand code. Usage of classes and methods is easy to understand. In addition, you have used comments for higher clarity in your code. 

I can feel comfortable about modifying your code. Your code does what it is supposed to do. Nothing more, nothing less.You divide your code in proper pieces and this make me happy when I try to change some parts of your code.  But, some code documentation can be needed. Because, I start to feel this comfortability after I ask you some questions about your code. Even if I didn’t do that, I can understand how to modify but in that case, I needed more time. That's why , some docs for your code can be great advantage for your team-mates.

I have tested your code to see whether it works and it does great job without error or bug. But unit tests can be added to it. It can help finding problems early, facilitating changes and simplifying integration.

Keep up the good work!

**Comment by tuba-topaloglu** [comment]
Thank you for your feedback. Unit tests will be implemented later by another team member. You are right, there are no comments in my code :) I will add more comments when I tidy up my code, because first I write my codes to catch a deadline and then clear it to make more understandable and maintainable.
